language: node_js
node_js: '10'
cache: yarn
script: yarn test:ci
before_deploy: yarn build
deploy:
  - provider: pages
    skip-cleanup: true
    local-dir: storybook-static
    github-token:
      secure: jCoyS5uSzMAcBklLXp6nc2Fix5GmuieWjzhG7tCwYoh1vrbDpssZ0l18yCXIVlVqPXj5L61ygYazfrnidFcoR/3V3/ugIpNpWiKD5CGBtE2as8DDw89DAXdVDDp2VVLK9CZHOcyY2CH/OgHXqgJtj/8iXHQzzQZAbsn/fplGd2/RaWPXoQLvUfom4bhlVYYSnDov1JahsmR0zXIkop0cxQZipqYTypviUHl8AtvgsgxU9Fnnwr0joylrt/N+cSGaeCZ4wc3xFYyHwDsQfOhXEXbndVMeYWzMtZscJa0/k1T+iYeeeHF5+h4HPQGm7C08dG/SwJsiFPDx1G/7WNeP1q0HvfsCf+5/wQ9UTgo4My15qVgUKRpaHO+n4QPaGJwm+JjCfcWpPyEzKxo6v0MzbagqyJKJNUrNP7dGB5QTahjNzdsMk6zLNJNueWE/Q4XFqZC7CxrrkGsx26uJ5goQbLb0lcRFkTcQGg51Nz8xz7ITxaLKsx1nDAN9SBvaZLxJyLeZMKP9yixR/J3XkadZsVOr4RyJpbSmues+3A9GpSwJUDdAhoV0lFqYwkVNSPB/+1CJsiNWlteqeMBzbBIEmPN2DTn9dcIjsUYoTGFrpf+DQjAlltV3peVBcVFTEN1puhSHvs+y5Fh6ZTYmcDUGI/DrgSOZgdfKfcsFML9auA8=
    keep-history: true
    on:
      branch: master
  - provider: npm
    skip-cleanup: true
    email: matt@teamdavies.co.uk
    api_key:
      secure: NhVi/KSWRMUa210cXMAmP+8VcTIYbpDF0FfI6E6wYk5e5UCoZYGGUe73pzRArmLttb0M56IjGa7TxNvgYSpl6mveZV1EHlqxojLVz90fTAlcKPLIQ/U6TKhDoG6pCcQ+/9emTiMeVlY/9edzwNIEzffsZ35L6LYEk7ScSj0VQcwfsuX7PYoyF+2z5vOsqL+cphcpfdiWdQfrMuQRXbmrdmDeL1zMnawZl+L2HcG/aLT+DdqqYneOBT2MaIo0u8qRuQeN7XREnj8lWnFZSIQKXftfjrctCbry025GgN8AUEMLTmN/fVUoamc15b4Bc/tVsC4oNsP68uW3AhQGGmdAjJoWcoIsTxaA1doxBPd+68phyq+ttrW5Od2tIOrRx1iaoiV3kt8GzDLJLX/f472NTcxLFgZU0mADcAIWMQ0UZ7ChOgY+koag08eAEy2qcSfF/WmfqE6mngXDDg6BmO6MJe01BvTZw+jbdNyOZMWTvEyJgysLAgFDg7cIhRej9KkDgU9tLG9pjNOjyxADYu+WFbZxzPFr/+suOPLuDJ7akhAVDZjO0VkyvyqjpxgnQY7c7h3l20A1emW52KWGMoSV2aAi6vFUX6/qFJlw9+p4sO6Qm9+lVyd+JK/m7lZGkqNIfZ8AOwc8v79tstwUqcRus8BEBq4f3o+4btI2i8grL9o=
    on:
      tags: true
      repo: AnomalousTechnologies/newton
notifications:
  slack:
    rooms:
      secure: m3GAr8Ds+maEJyfKMVqg8NlTX66flSuCr/X0I9YqY896/XRB1GNksQyLLNIRU5ZAPthpI16F95NmlzMOjq9N5M5rgCOfBSISFwR2QeXFQ20BwBjnFxkGmXS/ZYgHlw+jZgdbRwn+3NhdosuSWYY1fOWrNOiGJIWYvoUGQczeYeYnEDEZQFsTBzb6dOFJ9nwFcGkbAEyPMZV7Z8u3DJ92366o9O3biuevNX30LusGlISvPdREZuKfRweZl1lcbWUDUm87/FXblPugR0XG7YTMcHPWmuEHIFwHpZrcZTeJvJqpCdx+J8SUwLIHQk0075qCyLU/jSLQ7whCbCf52f9zET37ibtM1eluvoovnd43WEfFDQNBKE0VPX0JnVoVm0tAdd7t7NLcaz+CfS3gjLpx350XYlrF9j+y8ffTrAkKwpwcHHfpW4nUZR38VHqZxlD1QFlwoHovdvUPYWiXse/Hvf4Ik/8DJODYmKykkqwypm0NPjNgDM6hpBUC5U5zcEJB9n3t+2jDMKK3bvyMg4FieJairh0skZ9kVf2pJQkugzM0VMVPM/tJy4g892/ooX9/54yZ6u9g//GVxoNw5osEvQBbD1Hu93PKC+P1es4VE2IfcxGj3q5cC+gnV+UjByQlQ0VYZLrpGtME2XljEM2LEV66xk9eyWsnFWeVwUCrtvo=
